docking_pose_node:
  ros__parameters:
    # 模板文件配置
    pcd_file: "" # 空字符串，自动查找最新模板
    pcd_dir: "$(find-pkg-share docking_pose_estimator)/template/deploy/"
    
    # 话题配置
    pointcloud_topic: "/camera/depth/color/points"
    pose_topic: "/docking_pose"
    template_cloud_topic: "/template_cloud"
    transformed_cloud_topic: "/transformed_cloud"
    aligned_cloud_topic: "/aligned_cloud"
    
    # 点云处理参数
    voxel_size: 0.01
    
    # 坐标系配置
    camera_frame: "camera_depth_optical_frame"
    robot_frame: "base_footprint"
    docking_frame: "docking_target"
    
    # 滤波范围参数（单位：米）
    x_min: 0.0
    x_max: 2.0
    y_min: -1.0
    y_max: 1.0
    z_min: 0.2
    z_max: 1.5
    
    # 初始位姿猜测参数（平移单位：米，旋转单位：度）
    initial_x: 0.0
    initial_y: 0.0
    initial_z: 0.0
    initial_roll: 0.0
    initial_pitch: 0.0
    initial_yaw: 0.0
